#!/bin/sh

usage() {
  echo "./init <package-name>"
}

script_dir="$(realpath "$(dirname "$0")")"

if [ "$#" != "2" ]; then
  usage
  exit 1
fi

organization="$1"
package_name="$2"
repo_name="$(git remote get-url origin)"

sed -i "s/package-name/$package_name/" "$script_dir/.yarnrc"
sed -i "s/package-name/@$organization\\/$package_name/" "$script_dir/package.json"
sed -i "s/repo-name/${repo_name//\//\\/}/" "$script_dir/package.json"
